### ISSUE TITLE
How do you install yara?

### ISSUE THREAD

**Issue by kenorb** [Te-k/phpscanner#2]
It's:

```
pip install yara-python
```

or:

```
pip install yara
```

?

**Comment by Te-k** [comment]
You have to install them from source: http://yara.readthedocs.io/en/v3.4.0/gettingstarted.html#compiling-yara

By the way, this tool is mainly reusing [php-malware-scanner](https://github.com/planet-work/php-malware-scanner/) and [php-malware-finder](https://github.com/nbs-system/php-malware-finder/) and they have both evolved since the last update of thistool, so you should test them too
